version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./server:/usr/src/app
    links:
      - mongo
